CREATE TABLE player_t (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    xuid INTEGER NOT NULL UNIQUE,
    country TEXT,
    city TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
