CREATE TABLE tier_t (
    id SERIAL PRIMARY KEY,
    tier INTEGER NOT NULL UNIQUE CHECK (tier >= 1 AND tier <= 8),
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
